---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
  description: Hero image, if applicable
  showOnly:
    field: custom_embed_toggle
    value: false
- name: custom_embed_toggle
  type: boolean
  label: Custom Embed
  showOnly:
    value: true
- name: custom_embed
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Custom Embed
  showOnly:
    field: custom_embed_toggle
    value: true
- name: gallery
  type: blocks
  label: Gallery
  template_types:
  - image
  config:
    min: 
    max: 
pages:
- content/projects/tour/the-mirror-tour.md
