---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
  description: Hero image, if applicable
- name: gallery
  type: blocks
  label: Gallery
  template_types:
  - image
  config:
    min: 
    max: 
pages:
- content/projects/tour/the-mirror-tour.md
